before_install: gem install nokogiri
language: ruby
sudo: false
rvm:
- 2.5.3
cache: bundler
addons:
  apt:
    packages:
    - aspell
    - aspell-en
install:
- travis_retry bundle install
script:
- rake